export const SESSION_MAX_INACTIVE_TIME = 45;
export const SESSION_END_TIME_UPDATE_INTERVAL = 1;
export const SESSION_END_TIME_UPDATE_INTERVAL_IN_MS = SESSION_END_TIME_UPDATE_INTERVAL * 60 * 1000;
export const START_PERIOD_RETRY_INTERVAL = 5 * 1000;