export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const UPLOAD_CSV = "UPLOAD_CSV";
export const GET_BATCH_TRANSACTION = "GET_BATCH_TRANSACTION";
export const BATCH = "BATCH";
export const DELETE_BATCH = "DELETE_BATCH";
export const EXECUTE_BATCH_PAYOUT = "EXECUTE_BATCH_PAYOUT";
export const USER_ACCOUNT_BALANCE = "USER_ACCOUNT_BALANCE";

export const GET_TRANSACTION = "GET_TRANSACTION";

export const HISTORY_DATA = "HISTORY_DATA";
export const USER_DATA = "USER_DATA";
export const INVITE_USER = "INVITE_USER";
export const EXPORT_FILE = "EXPORT_FILE";
export const SEARCH_DATA = "SEARCH_DATA";
export const SEARCH_USER = "SEARCH_USER";
export const USER_STATUS = "USER_STATUS" ;
export const SEARCH_TRANSACTION = "SEARCH_TRANSACTION" ;
export const ADMIN_TRANSACTION =  "ADMIN_TRANSACTION" ;
export const MERCHANT_DATA = "MERCHANT_DATA" ;
export const MERCHANT_SEARCH = "MERCHANT_SEARCH" ; 
export const BATCH_TRANSACTION = "BATCH_TRANSACTION" ;
export const MERCHANT_STATUS = "MERCHANT_STATUS" ;
export const ADD_MERCHANT = "ADD_MERCHANT"
export const EDIT_MERCHANT_BRAND = "EDIT_MERCHANT_BRAND"
export const DELETE_BRAND = "DELETE_BRAND"
export const EDIT_BRAND_DETAILS = "EDIT_BRAND_DETAILS"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const API_KEY_DATA = "API_KEY_DATA"
export const VERIFY_PASSWORD  = "VERIFY_PASSWORD"

export const NEW_PASSWORD = "NEW_PASSWORD"
export const CONSENT = "CONSENT";
export const LINK_EXPIRY = "LINK_EXPIRY";
